appl/routes.py
from functools import wraps

from flask import Blueprint, request, session, redirect, url_for, render_template_string, render_template, Response, \
    jsonify

routes_in_routes = Blueprint('routes_in_routes', __name__)


@routes_in_routes.before_app_first_request
def prefill_db():
    from app import db
    from models import Biostat
    db.session.query(Biostat).delete()
    db.session.commit()
    try:
        for csv_row in open("../db/init.csv", "r"):
            line = csv_row.strip().split(",")
            print(line)
            names = line[0]
            sex = line[1]
            age = line[2]
            height_in = line[3]
            weight_lbs = line[4]
            b = Biostat(names=names, sex=sex, age=age, height_in=height_in, weight_lbs=weight_lbs)
            db.session.add(b)
            db.session.commit()
    except:
        print("out")
    finally:
        print("in")


def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if session.get('email') is None:
            return redirect(url_for('routes_in_routes.get_email'), code=302)
        return f(*args, **kwargs)

    return decorated_function


@routes_in_routes.route('/', methods=['GET'])
@login_required
def index():
    from appl.models import Biostat
    user = {'username': 'Biostat Project'}
    biostat = Biostat.query.order_by(Biostat.id)
    return render_template('index.html', title='Home', user=user, biostat=biostat)


@routes_in_routes.route('/view/<int:biostat_id>', methods=['GET'])
@login_required
def record_view(biostat_id):
    from appl.app import db
    from appl.forms import BiostatForm
    from appl.models import Biostat
    # print(db.session.query().filter_by(id=address_id).first())
    print(Biostat.query.get(biostat_id).names)
    return render_template('view.html', title='View Form', biostat=Biostat.query.get(biostat_id))


@routes_in_routes.route('/edit/<int:biostat_id>', methods=['GET'])
@login_required
def form_edit_get(biostat_id):
    from appl.models import Biostat
    biostat = Biostat.query.filter_by(id=biostat_id).one()
    return render_template('edit.html', title='Edit Form', biostat=biostat)


@routes_in_routes.route('/edit/<int:biostat_id>', methods=['POST'])
@login_required
def form_update_post(biostat_id):
    from app import db
    from appl.models import Biostat
    biostat = Biostat.query.filter_by(id=biostat_id).one()
    biostat.names = request.form.get('names')
    biostat.sex = request.form.get('sex')
    biostat.age = request.form.get('age')
    biostat.height_in = request.form.get('height_in')
    biostat.weight_lbs = request.form.get('weight_lbs')
    # print(biostat.weight_lbs)
    db.session.flush()
    db.session.commit()
    return redirect("/", code=302)


@routes_in_routes.route('/biostat/new', methods=['POST'])
@login_required
def form_insert_get():
    from appl.app import db
    from appl.forms import BiostatForm
    from appl.models import Biostat
    form = BiostatForm()
    biostat = Biostat(names=form.names.data, sex=form.sex.data, age=form.age.data,
                      height_in=form.height_in.data, weight_lbs=form.weight_lbs.data)
    print(biostat.weight_lbs)
    names = form.names
    db.session.add(biostat)
    db.session.commit()
    # remove
    form.names.data = ''
    form.sex.data = ''
    form.age.data = ''
    form.height_in.data = ''
    form.weight_lbs.data = ''
    biostat = Biostat.query.order_by(Biostat.id)
    return render_template('new.html', title='New Biostat Form', form=form, names=names, biostat=biostat)


@routes_in_routes.route('/biostat/new', methods=['GET'])
@login_required
def form_insert_post():
    from appl.app import db
    from appl.forms import BiostatForm
    from appl.models import Biostat
    form = BiostatForm()
    biostat = Biostat.query.order_by(Biostat.id)
    return render_template('new.html', title='New Biostat Form', form=form, biostat=biostat)
    return redirect("/", code=302)


@routes_in_routes.route('/delete/<int:biostat_id>', methods=['POST'])
@login_required
def form_delete_post(biostat_id):
    from app import db
    from appl.models import Biostat
    biostat = Biostat.query.filter_by(id=biostat_id).one()
    # print(biostat.age)
    db.session.delete(biostat)
    db.session.commit()
    return redirect("/", code=302)


@routes_in_routes.route('/api/v1/biostat', methods=['GET'])
def api_browse() -> str:
    from appl.app import db
    from appl.forms import BiostatForm
    from appl.models import Biostat
    resp = Biostat.query.all()
    json_res = []
    for temp in resp:
        json_res.append(temp.toDict())
    return jsonify(json_res)


@routes_in_routes.route('/api/v1/biostat/<int:biostat_id>', methods=['GET'])
def api_retrieve(biostat_id) -> str:
    from appl.app import db
    from appl.forms import BiostatForm
    from appl.models import Biostat
    resp = Biostat.query.filter_by(id=biostat_id).one()
    return jsonify(resp.toDict())


@routes_in_routes.route('/api/v1/biostat', methods=['POST'])
def api_add() -> str:
    from appl.app import db
    from appl.forms import BiostatForm
    from appl.models import Biostat
    content = request.json
    biostat = Biostat(names=content['names'], sex=content['sex'], age=content['age'],
                      height_in=content['height_in'], weight_lbs=content['weight_lbs'])
    db.session.add(biostat)
    db.session.commit()
    resp = Response(status=201, mimetype='application/json')
    return resp


@routes_in_routes.route('/api/v1/biostat/<int:biostat_id>', methods=['PUT'])
def api_edit(biostat_id) -> str:
    from appl.app import db
    from appl.models import Biostat
    from flask import request, Response
    content = request.json
    biostat = Biostat.query.filter_by(id=biostat_id).one()
    biostat.names = content['names']
    biostat.sex = content['sex']
    biostat.age = content['age']
    biostat.height_in = content['height_in']
    biostat.weight_lbs = content['weight_lbs']
    db.session.commit()
    resp = Response(status=200, mimetype='application/json')
    return resp



@routes_in_routes.route('/api/v1/biostat/<int:biostat_id>', methods=['DELETE'])
def api_delete(biostat_id) -> str:
    from app import db
    from appl.models import Biostat
    biostat = Biostat.query.filter_by(id=biostat_id).one()
    db.session.delete(biostat)
    db.session.commit()
    resp = Response(status=200, mimetype='application/json')
    return resp


@routes_in_routes.route('/set_email', methods=['GET', 'POST'])
def set_email():
    if request.method == 'POST':


        from appl.models import Signup
        username = request.form['username']
        password = request.form['password']
        user_obj = Signup.query.filter_by(username=username).first()
        if user_obj is not None:
            if username == user_obj.username and password == user_obj.password:
                session['email'] = request.form['username']
                return redirect(url_for('routes_in_routes.index'))
            else:
                return render_template_string("""
                    Invalid Password. Please try again!
                    <h3><a href="{{ url_for('routes_in_routes.get_email') }}">Back</a></h3>
                """)
        else:
            return render_template_string("""
                                Username not found!
                                 <h3><a href="{{ url_for('routes_in_routes.get_email') }}">Back</a></h3>
                            """)



        #return redirect(url_for('routes_in_routes.get_email'))

    return """
        <form method="post">
        <h1>Login Page</h1>
            <label for="email">Username:</label>
            <input type="username" id="username" name="username" required />
             <label for="password">Password:</label>
            <input type="password" id="password" name="password" required />  
            <button type="submit">Submit</button
        </form>
        """
    # if request.method == 'POST':
    #     session['email'] = request.form['email_address']
    #     return redirect(url_for('routes_in_routes.get_email'))
    #
    # return """
    #        <form method="post">
    #            <label for="email">Enter your email address:</label>
    #            <input type="email" id="email" name="email_address" required />
    #            <button type="submit">Submit</button
    #        </form>
    #        """

# uselessssssssssss--------------------------------
# @routes_in_routes.route('/get_email', methods=['GET', 'POST'])
# def get_email():
#     from appl.app import db
#     from appl.forms import SignupForm
#     from appl.models import Signup
#     sform = SignupForm()
#     username = sform.username.data
#     password = sform.password.data
#     user_obj = Signup.query.filter_by(username=username).one()
#     if username == user_obj.username and password == user_obj.password:
#         return redirect(url_for('routes_in_routes.index'))
#     else:
#         return render_template_string("""
#          <h1>Welcome! <h1>
#          <h2> <a href="{{ url_for('routes_in_routes.set_email') }}">Login</a></h>
#          <h2><a href="{{ url_for('routes_in_routes.signup') }}">Signup</a></h2>
#         """)



@routes_in_routes.route('/get_email')
def get_email():
    return render_template_string("""
            {% if session['email'] %}
                <h1> <a href="{{ url_for('routes_in_routes.index') }}">Go to HomePage</a> </h1>
            {% else %}
                <h1>Welcome! <h1>
                <h2> <a href="{{ url_for('routes_in_routes.set_email') }}">Login</a></h>
                <h2><a href="{{ url_for('routes_in_routes.signup') }}">Signup</a></h2>
            {% endif %}
        """)


@routes_in_routes.route('/delete_email')
def delete_email():
    # Clear the email stored in the session object
    session.pop('email', default=None)
    return '<h1>Session deleted!</h1>'


@routes_in_routes.route('/signup', methods=['POST', 'GET'])
def signup():

templates/edit.html
{% extends "layout.html" %}
{% block content %}
<form action="/edit/{{biostat.id}}" method="post">
    <div class="row">
        <div class="col">
            <label for="names">Name</label>
            <input id="names" type="text" class="form-control" placeholder="Name" name="names" value="{{biostat.names}}">
        </div>
        <div class="col">
            <label for="sex">Sex</label>
            <input id="sex" type="text" class="form-control" placeholder="Sex"
                   name="sex" value="{{biostat.sex}}">
        </div>
        <div class="col">
            <label for="age">Age</label>
            <input id="age" type="text" class="form-control" placeholder="Age" name="age" value="{{biostat.age}}">
        </div>
    </div>
    <div class="row">
        <div class="col">
            <label for="height_in">Height (inches)(</label>
            <input id="height_in" type="text" class="form-control" placeholder="Height (inches)" name="height_in" value="{{biostat.height_in}}">
        </div>
        <div class="col">
            <label for="weight_lbs">Weight (lbs)</label>
            <input id="weight_lbs" type="text" class="form-control" placeholder="Weight (lbs)" name="weight_lbs" value="{{biostat.weight_lbs}}">
        </div>
    </div>
    <button type="submit" class="btn btn-success">Save</button>

</form>
{% endblock %}

templates/index.html
{% extends "layout.html" %}
{% block content %}
<table class="table">
    <thead>
    <tr>
        <th scope="col">Name</th>
        <th scope="col">Age</th>
        <th scope="col">Sex</th>
        <th scope="col">Height (inches)</th>
        <th scope="col">Weight (lbs)</th>
    </tr>
    </thead>
    <tbody>
    {% for val in biostat %}
    <tr>
        <td><a href="view/{{val.id}}">{{ val.names }}</a></td>
        <td>{{ val.sex }}</td>
        <td>{{ val.age }}</td>
        <td>{{ val.height_in }}</td>
        <td>{{ val.weight_lbs }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
    <a href="{{ url_for('routes_in_routes.delete_email') }}">Logout</a>
{% endblock %}

templates/layout.html
<!doctype html>
<html lang="en">
<head>

    <!-- Required meta tags -->

    <!-- Bootstrap CSS -->


    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" rel="stylesheet">
{% if user %}
    <title>Welcome to {{ user.username }}'s site</title>
    {% else %}
    <title>Welcome to My Site!</title>
    {% endif %}
<head>
 <body>
<!-- As a heading -->


<nav class="navbar navbar-expand-lg navbar-light bg-light mb-1">
  <a class="navbar-brand" href="#">{% if user %}{{ session['email'] }}'s Homepage{% else %}
    <title>Welcome to My Homepage</title>
    {% endif %}</a>
  <button aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbarNavDropdown" data-toggle="collapse" type="button">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
        <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="/api/v1/biostat">Address's API JSON endpoint <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
            <a class="btn btn-success pl-2 lr-2 ml-3" href="/biostat/new">Add +<span class="sr-only">(current)</span></a>
        </li>
    </ul>
  </div>
</nav>
<main class="container" role="main">

    {% block content %}
    {% endblock %}
</main>
<div id="footer">
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
     <script crossorigin="anonymous"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script crossorigin="anonymous"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script crossorigin="anonymous"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</div>
</body>
</html>

templates/new.html
{% extends "layout.html" %}
{% block content %}
<form action="/biostat/new" method="POST">
    <div class="row">
        <div class="col">
            <label for="names">Name</label>
            <input id="names" type="text" class="form-control" placeholder="Name" name="names">
        </div>
        <div class="col">
            <label for="sex">Sex</label>
            <input id="sex" type="text" class="form-control" placeholder="Sex"
                   name="sex">
        </div>
        <div class="col">
            <label for="age">Age</label>
            <input id="age" type="text" class="form-control" placeholder="Age" name="age">
        </div>
    </div>
    <div class="row">
        <div class="col">
            <label for="height_in">Height (inches)(</label>
            <input id="height_in" type="text" class="form-control" placeholder="Height" name="height_in">
        </div>
        <div class="col">
            <label for="weight_lbs">Weight (lbs)</label>
            <input id="weight_lbs" type="text" class="form-control" placeholder="Weight" name="weight_lbs">
        </div>
    </div>
    <button type="submit" class="btn btn-success">Create</button>

</form>

{% endblock %}

templates/signup.html
{% block content %}
<form action="/signup" method="POST">
<h1>SignUp Page</h1>
    <div class="row">
        <div class="col">
            <label for="username">Username</label>
            <input id="username" type="text" class="form-control" placeholder="Username" name="username">
        </div>
        <div class="col">
            <label for="password">Password</label>
            <input id="password" type="text" class="form-control" placeholder="Password"
                   name="password">
        </div>
    <button type="submit" class="btn btn-success">Signup</button>
        <a href="{{ url_for('routes_in_routes.get_email') }}">Back</a>
    </div>
</form>

{% endblock %}

templates/view.html
{% extends "layout.html" %}
{% block content %}

<div class="card" class="m-5 p-2">
    <h5 class="card-title">{{ biostat.names }}</h5>

    <ul class="list-group list-group-flush">
        <li class="list-group-item">Name: {{ biostat.names }}</li>
        <li class="list-group-item">Sex: {{ biostat.sex }}</li>
        <li class="list-group-item">Age: {{ biostat.age }}</li>
        <li class="list-group-item">Height (inches): {{ biostat.height_in }}</li>
        <li class="list-group-item">Weight (lbs): {{ biostat.weight_lbs }}</li>
    </ul>
    <div class="card-body">
        <a href="/edit/{{biostat.id}}" class="card-link btn btn-primary">Edit</a>
    </div>
</div>
<form action="/delete/{{biostat.id}}" method="post"><button type="submit" class="btn btn-danger">Delete</button></form>


{% endblock %}